[project]
name = "stacked-prs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wassim Seifeddine", email = "wassim_seifeddine95@live.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
stacked-prs = "stacked_prs:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
